from playwright.sync_api import sync_playwright
import os
OUT = os.path.join("outputs", "pin-check")
os.makedirs(OUT, exist_ok=True)
with sync_playwright() as p:
    b = p.chromium.launch()
    pg = b.new_page(viewport={"width": 390, "height": 844}, is_mobile=True, has_touch=True)
    errs = []
    pg.on("pageerror", lambda e: errs.append(str(e)))
    pg.goto("http://127.0.0.1:5173/?create", wait_until="networkidle")
    pg.wait_for_timeout(600)
    pg.locator(".create__confirm input").check()
    pg.locator(".recover__go").click()
    pg.wait_for_selector(".pin", state="visible")
    pg.wait_for_timeout(400)
    print("PIN title:", pg.locator(".pin__title").first.text_content())
    print("back visible:", pg.locator(".pin__back").count() > 0)
    print("slots:", pg.locator(".pin__slot").count())
    print("keys:", pg.locator(".pin__keys .send-key").count())
    print("cta disabled empty:", pg.locator(".pin__cta").is_disabled())
    pg.screenshot(path=os.path.join(OUT, "pin-empty.png"))
    for d in ["1", "2", "3", "4"]:
        pg.locator(".pin__keys .send-key", has_text=d).first.click()
        pg.wait_for_timeout(120)
    print("slot texts:", [pg.locator(".pin__slot").nth(i).text_content() for i in range(4)])
    print("cta disabled full:", pg.locator(".pin__cta").is_disabled())
    print("cta label:", pg.locator(".pin__cta").text_content())
    pg.screenshot(path=os.path.join(OUT, "pin-filled.png"))
    pg.locator(".pin__cta").click()
    pg.wait_for_timeout(1200)
    print("cta working:", pg.locator(".pin__cta").text_content())
    pg.screenshot(path=os.path.join(OUT, "pin-working.png"))
    pg.wait_for_timeout(3200)
    print("cta done:", pg.locator(".pin__cta").text_content())
    pg.screenshot(path=os.path.join(OUT, "pin-done.png"))
    pg.wait_for_selector(".wallet", state="visible", timeout=15000)
    print("wallet reached:", pg.locator(".wallet__balance").count() > 0)
    pg.screenshot(path=os.path.join(OUT, "wallet-after-pin.png"))
    print("console errors:", errs)
    b.close()
print("PIN CHECK OK")
